language: python

python:
  - 2.7

branches:
  only:
    - master
    - development

notifications:
  email:
    - janssen@physik.uni-bonn.de
    - pohl@physik.uni-bonn.de

# Install additional dependencies required by pyBAR
before_install:
  - sudo add-apt-repository -y ppa:team-electronics/ppa
  - sudo apt-get -q update
  - sudo apt-get -q install iverilog-daily

# Install pyBAR and dependencies
install:
  - wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda update --yes --all
  - conda info -a
  - conda create --yes -n test-environment python=$TRAVIS_PYTHON_VERSION bitarray cython ipython matplotlib mock nose numba numpy pyserial pytables pyyaml pyzmq scipy sphinx
  - source activate test-environment
  - pip install progressbar-latest pyvisa pyvisa-py git+https://github.com/pyqtgraph/pyqtgraph.git@pyqtgraph-0.10.0 #git+https://github.com/uvemas/ViTables@develop
  - git clone https://github.com/potentialventures/cocotb
  - export COCOTB=$(pwd)/cocotb
  - pip install pyusb
  - pip install pySiLibUSB
  - if [ "$TRAVIS_BRANCH" == "master" ]; then pip install 'basil_daq>=2.4.9,<3.0.0' git+https://github.com/SiLab-Bonn/pyBAR_fei4_interpreter@development 'pixel_clusterizer>=3.1,<3.2'; fi
  - if [ "$TRAVIS_BRANCH" == "development" ]; then pip install 'basil_daq>=2.4.9,<3.0.0' git+https://github.com/SiLab-Bonn/pyBAR_fei4_interpreter@development 'pixel_clusterizer>=3.1,<3.2'; fi
  # Build iverilog from source
#  - sudo apt-get install gperf
#  - wget -O iverilog-master.zip  https://github.com/steveicarus/iverilog/archive/master.zip
#  - unzip iverilog-master.zip
#  - cd iverilog-master && autoconf && ./configure && make && sudo make install && cd ..
  # Install pybar
  - python setup.py develop


# Unit tests
script:
  # Remove file to make interface test working
#  - rm -f /home/travis/miniconda/envs/test-environment/lib/libreadline.so.6
  - cd pybar/testing; nosetests test_analysis.py test_interface.py # --logging-level=INFO
