build: false  # Tell appveyor to not use msbuild

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "32"
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
      PYTHON_ARCH: "64"
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37
      PYTHON_ARCH: "32"
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37-x64
      PYTHON_ARCH: "64"

# platform:
#   - x86
#   - x64

init:
  # - ps: Start-FileDownload 'http://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi' C:\VCForPython27.msi; echo "Done"
  # - cmd: msiexec /i C:\VCForPython27.msi /quiet /qn

install:
  # Miniconda setup + necessary external packages
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;%MINICONDA%\Library\bin;%PATH%
  - conda update conda --yes
  - conda info -a
  - conda install --yes bitarray contextlib2 cython ipython matplotlib mock nose numba numpy pyqt pyserial pytables pyyaml pyzmq qtpy scipy tqdm
  - pip install pyvisa pyvisa-py git+https://github.com/pyqtgraph/pyqtgraph.git@pyqtgraph-0.10.0 #git+https://github.com/uvemas/ViTables@develop
  # test packages required for USB interface
  - pip install pyusb
  - pip install pySiLibUSB
  # pyBAR installation including additional specific packages
  - pip install "basil_daq>=2.4.12,<4.0.0"
#  - pip install git+https://github.com/SiLab-Bonn/basil@development
  - pip install "pyBAR_fei4_interpreter>=1.5,<2.0"
#  - pip install git+https://github.com/SiLab-Bonn/pyBAR_fei4_interpreter@development
  - pip install "pixel_clusterizer>=3.1,<3.2"
  - pip install -e .
  - conda list

test_script:
  - cd pybar/testing
  - nosetests --nocapture test_analysis.py
