
USB:
    bit_file       : "mio.bit"
    board_id       : 
    avoid_download : False

CMD:
    OUTPUT_MODE : 0  # 0: positive edge (default), 2: Manchester code

TLU:
    TRIGGER_MODE        : 0
    EN_INVERT_TRIGGER   : 0
    EN_WRITE_TIMESTAMP  : 0
    TRIGGER_LOW_TIMEOUT : 255

CH4:
    INVERT_RX : 0  # 0: IBL modules (default), 1: DBM modules

CH3:
    INVERT_RX : 0
    
CH2:
    INVERT_RX : 0

CH1:
    INVERT_RX : 0
