
USB:
    bit_file       : "mio.bit"
    board_id       : 
    avoid_download : False

CMD:
    OUTPUT_MODE : 0  # 0: positive edge (default), 2: Manchester code

TLU:
    TRIGGER_MODE        : 0
    TRIGGER_SELECT      : 0 # TDC_IN_FROM_TDC, LEMO_TRIGGER_FROM_TDC, MONHIT
    TRIGGER_INVERT      : 0
    TRIGGER_VETO_SELECT : 255 # VETO_IN, FIFO_FULL

CH4:
    INVERT_RX : 0  # 0: IBL modules (default), 1: DBM modules

CH3:
    INVERT_RX : 0
    
CH2:
    INVERT_RX : 0

CH1:
    INVERT_RX : 0
