
USB:
    bit_file       : "mio_gpac.bit"
    board_id       : 
    avoid_download : False

CMD:
    OUTPUT_MODE : 0  # 0: positive edge (default), 2: Manchester code

TLU:
    TRIGGER_MODE        : 0
    EN_INVERT_TRIGGER   : 0
    EN_WRITE_TIMESTAMP  : 0
    TRIGGER_LOW_TIMEOUT : 255
